import type { VehicleProfile } from '../types';

export const PROFILES: Record<string, VehicleProfile> = {
    car: {
        key: 'car',
        path: 'osrm',
        label: 'Carro',
        icon: '🚗',
        color: '#3b82f6',
        specs: '2.0m alto • 1.9m ancho • 2T',
        height: 2,
        width: 1.9,
        weight: '2T',
        vroomProfile: 'car',
    },
    moto: {
        key: 'moto',
        path: 'osrm/moto',
        label: 'Moto',
        icon: '🏍️',
        color: '#f97316',
        specs: '1.5m alto • 1.0m ancho • 300kg',
        height: 1.5,
        width: 1,
        weight: '300kg',
        vroomProfile: 'moto',
    },
    van: {
        key: 'van',
        path: 'osrm/van',
        label: 'Van',
        icon: '🚐',
        color: '#14b8a6',
        specs: '2.6m alto • 2.2m ancho • 3.5T',
        height: 2.6,
        width: 2.2,
        weight: '3.5T',
        vroomProfile: 'van',
    },
    truck_medium: {
        key: 'truck_medium',
        path: 'osrm/medium',
        label: 'Camión',
        icon: '🚚',
        color: '#f59e0b',
        specs: '3.8m alto • 2.5m ancho • 10T',
        height: 3.8,
        width: 2.5,
        weight: '10T',
        vroomProfile: 'truck_medium',
    },
    truck_heavy: {
        key: 'truck_heavy',
        path: 'osrm/heavy',
        label: 'Pesado',
        icon: '🚛',
        color: '#ef4444',
        specs: '4.5m alto • 2.6m ancho • 40T',
        height: 4.5,
        width: 2.6,
        weight: '40T',
        vroomProfile: 'truck_heavy',
    },
};

export const PROFILE_KEYS = Object.keys(PROFILES);
